namespace: egov
name: s3-proxy

cluster-configs:
  configmaps:
    egov-config:
      data:
        s3-assets-bucket: "(pb-egov-assets|egov-dev-assets)"

externalName: s3.eu-north-1.amazonaws.com
httpPort: 80
type: ExternalName